# Generated by Django 3.2 on 2021-04-21 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0001_initial'),
        ('SCRUM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created', to='login_reg.user'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
